package main

import (
	"fmt"
	"os"
	"radlang/compiler"
	"radlang/lexer"
	"radlang/parser"
	"radlang/semantic"
	"radlang/vm"
	"strings"
)

func main() {
	// if len(os.Args) < 2 {
	// 	fmt.Fprintln(os.Stderr, "usage: radlang <file>")
	// 	os.Exit(1)
	// }
	// fileName := os.Args[1]
	// file, err := os.ReadFile(fileName)
	file, err := os.ReadFile("../tests/arithmetic.rad")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Printf("%s\n", string(file))
	fmt.Printf("Lexer Output:\n")
	fmt.Printf("%-4s %-16s %s\n", "Line", "Type", "Lexeme")
	fmt.Printf("%-4s %-16s %s\n", "----", "----", "------")
	tokens := lexer.Lex(string(file))
	for _, val := range tokens {
		fmt.Println(val)
	}
	fmt.Printf("\nAST:\n")
	ast, err := parser.Parse(tokens)
	if err != nil {
		fmt.Printf("Parse error: %v\n", err)
		return
	}
	printAST(ast)

	globalScope, report := semantic.Analyze(ast)
	if report != nil {
		fmt.Printf("Semantic Analysis returned: ")
		semantic.Report(report)
		return
	}

	bytecode, err := compiler.Compile(ast, globalScope)
	if err != nil {
		panic("Unknown error in compilation")
	}
	fmt.Printf("\nGenerated Bytecode:\n")
	compiler.Disasm(bytecode)
	vm.Execute(*bytecode)
}

func printAST(program *parser.Program) {
	fmt.Println("Program")
	for _, fn := range program.Functions {
		printFuncDecl(fn, 1)
	}
	for _, s := range program.Structs {
		fmt.Printf("  Struct_Decl: %s\n", s.Name)
		for _, field := range s.Body.Statement_Group {
			fmt.Printf("    Decl_stmt: %v %v\n", field.Name, field.Type)
		}
	}
	for _, iface := range program.Interfaces {
		fmt.Printf("  Interface_Decl: %s\n", iface.Name)
		for _, sig := range iface.Body.Statement_Group {
			printFuncSignature(sig, 2)
		}
	}
}

func printFuncDecl(fn *parser.Func_Decl, depth int) {
	pad := strings.Repeat("  ", depth)
	fmt.Printf("%sFunc_Decl: %s\n", pad, fn.Signature.Name)
	printFuncSignature(fn.Signature, depth+1)
	printBlock(fn.Body, depth+1)
}

func printFuncSignature(sig *parser.Func_Signature, depth int) {
	pad := strings.Repeat("  ", depth)
	for _, p := range sig.Params {
		fmt.Printf("%sParam: %s %v\n", pad, p.Name, p.Type)
	}
	if len(sig.Returns) > 0 {
		fmt.Printf("%sReturns: %v\n", pad, sig.Returns)
	}
}

func printBlock(block *parser.Block, depth int) {
	pad := strings.Repeat("  ", depth)
	if block == nil {
		return
	}
	fmt.Printf("%sBlock\n", pad)
	for _, stmt := range block.Statement_Group {
		printStatement(stmt, depth+1)
	}
}

func printStatement(stmt parser.Statement, depth int) {
	pad := strings.Repeat("  ", depth)
	switch s := stmt.(type) {
	case *parser.Control_stmt:
		fmt.Printf("%sControl_stmt: if\n", pad)
		printExpr(s.Expression, depth+1)
		printBlock(s.IfBlock, depth+1)
		if s.ElseStmt != nil {
			fmt.Printf("%selse if\n", pad)
			printStatement(s.ElseStmt, depth)
		} else if s.ElseBlock != nil {
			fmt.Printf("%selse\n", pad)
			printBlock(s.ElseBlock, depth+1)
		}
	case *parser.Decl_stmt:
		fmt.Printf("%sDecl_stmt: %v %v\n", pad, s.Name, s.Type)
	case *parser.Assign_stmt:
		fmt.Printf("%sAssign_stmt: %v op=%v\n", pad, s.Targets, s.Op)
		for _, v := range s.Values {
			printExpr(v, depth+1)
		}
	case *parser.Loop_stmt:
		fmt.Printf("%sLoop_stmt:\n", pad)
		printExpr(s.Expression, depth+1)
		printBlock(s.Loop_block, depth+1)
	case *parser.Expr_stmt:
		fmt.Printf("%sExpr_stmt:\n", pad)
		printExpr(s.Expression, depth+1)
	case *parser.Jump_stmt:
		fmt.Printf("%sJump_stmt: %v\n", pad, s.Type)
	case *parser.Return_stmt:
		fmt.Printf("%sReturn_stmt:\n", pad)
		for _, v := range s.Returns {
			printExpr(v, depth+1)
		}
	}
}

func printExpr(expr parser.Expression, depth int) {
	pad := strings.Repeat("  ", depth)
	switch e := expr.(type) {
	case *parser.Binary_expr:
		fmt.Printf("%sBinary_expr: %v\n", pad, e.Op)
		printExpr(e.Left, depth+1)
		printExpr(e.Right, depth+1)
	case *parser.Call_expr:
		fmt.Printf("%sCall_expr: %s()\n", pad, e.Name)
		for _, arg := range e.Args {
			printExpr(arg, depth+1)
		}
	case *parser.Identifier_expr:
		fmt.Printf("%sIdentifier_expr: %s\n", pad, e.Name)
	case *parser.Postfix_expr:
		fmt.Printf("%sPostfix_expr: %s\n", pad, e.Op)
		printExpr(e.Target, depth+1)
	case *parser.Lit_val:
		fmt.Printf("%sLiteral_Val: %s %s\n", pad, e.Type, e.Value)
	}
}
